version: "3.8"

services:
  web:
    build: .
    container_name: ormat-web
    ports:
      - "${PORT}:4205"
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
    restart: unless-stopped
